language: go
go:
- 1.10.x
env:
- GO_ENV=test
services:
- postgresql
before_script:
- psql -c 'create database brokernode_test;' -U postgres
- mkdir -p $TRAVIS_BUILD_DIR/public/assets
go_import_path: github.com/oysterprotocol/brokernode
install:
- go get github.com/gobuffalo/buffalo/buffalo
- go get $(go list ./... | grep -v /vendor/)
script: buffalo test
notifications:
  slack:
    secure: AWPF4SgT4QB0DHBOTZ5BLf0DQFsb9B9JUZyQWXVkR/cfLQp+duUDW4NMqs2TzNiZ/IwUkTNkoDclGXrQka3hhZ8gOQfmt86y6AqUlsxgHKgvalUgkbPAwSJWTUKv40/42dbZdqgpUbMoHNmakOZdxk6DvE/J4FX3AkhFnUxIaG4XqJyZITU/Iz0NQedy+D0RbY5kGaECQ5W65hiPNx2wCz8upuR/wBwq+PNx+RmrvsxP2XXw/RzCGzjDA1QycBYwVbV07n1Fvh7jiYz04F+qP7gKwrNlGsfhzvR+yLMTucx2JwORZhnwJ4TyNJj0uhyfcB7Dd0dsYFnwotGWIOGnSYYa6OmrabIzxlcZLecak1qsdupgSp4imaibE6LGz6+FmZ5HmAKWyULT/7vtBlsQIO4yYCjpzN8tUBM3xI5r4jkVLlX9dfcevBiCkG4j+gbMI4rOR6vWkxBBh8WVSTKr+np5+LKr+oRL+EVa8Eu8cA8SQ1vbgfUNH9OUpxINd8z2eP4Kd4iQ91nA+IRD/P62ngoEx4W9Jg7TqVUJ13YHLQLQfpCTPGSHYVYraJwtxE04J0zEvV6BfsZYe1b9pR5Y10zS1L8bCzNMmCXYDwaiGyyXcXs2tv+yjITcyV9WI/cXgBY93807U86PmbG2gJfDiU25/G040wNBjPA2kwufc3I=
