development:
  dialect: "mysql"
  database: "brokernode"
  host: "db"
  port: "3306"
  user: "root"
  password: "secret"

test:
  dialect: "mysql"
  database: "brokernode_test"
  host: "db_test"
  port: "3306"
  user: "root"
  password: "secret"

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/brokernode_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
