version: "3"

services:

  app:
    build: "."
    restart: "always"
    ports:
    - ${APP_PORT}:3000
    env_file:
    - ".env"
    depends_on:
    - "db"
    volumes:
    - ".:/go/src/github.com/oysterprotocol/brokernode"
    working_dir: "/go/src/github.com/oysterprotocol/brokernode"
    command: bash -c "buffalo db migrate && buffalo dev"

  db:
    image: "mysql:5.7"
    restart: "always"
    environment:
    - MYSQL_DATABASE=brokernode
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=secret
    volumes:
    - "./data/mysql:/var/lib/mysql"

